import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TanstackProvider from './components/providers/tanstack-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <div className='flex justify-center font-sans'>
            <div className="bg-slate-200 text-slate-900 w-[480px] h-full p-4 ">
              {children}
            </div>
          </div>
        </TanstackProvider>
      </body>
    </html>
  )
}
